spring.application.name=careerforge-backend

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/careerforge
spring.datasource.username=postgres
spring.datasource.password=vaishu25@S

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082